source 'https://rubygems.org'

path '../'

gemspec

group :development do # Development dependencies (as in the gemspec)
  # we can't use rake 11, 12 due to Rake 11.0.1 removes the last_comment method which rspec 2.99
  # uses
  gem 'rake', '< 11.0'
end
